name: CI slash command
on:
  workflow_dispatch:
    inputs:
      repo:
        default: "timroes/github-actions-test"
        required: false
      comment-id:
        description: "The comment-id of the slash command. Used to update the comment with the status."
        required: false

jobs:
  fake-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo }}
      - name: Debug
        uses: hmarr/debug-action@v2
      - name: Additional debug
        run: |
          echo "${{ github.repository }}"
          echo "${{ github.ref }}"