name: CI

on:
  push:
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    name: "Run CI script"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Script
        run: ./ci.sh
