name: CI

on:
  push:
    branches:
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest
    if: github.repository == 'timroes/github-actions-test'
    name: "Trigger CI run"
    uses: ./.github/workflows/pr-ci.yml@main
