name: CI on PR

on:
  pull_request_target:
  workflow_call:

jobs:
  fake-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run CI
        run: |
          echo "We would now be running CI"
          echo "${{ secrets.PAT }}"
      - name: Debug
        uses: hmarr/debug-action@v2